name: Deploy

on:
  push:
    branches: [master]
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: "Build and deploy website"
        if: github.repository_owner == 'meldgames'
        uses: shalzz/zola-deploy-action@710bd93a3824d642f387413f4e5669921a50c226
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
